### ISSUE TITLE
Missing functionality from vision in requirements

### ISSUE THREAD

**Issue by MaiNorapong** [ZEZAY/ku-polls#1]
### Requirements

The ability for users who voted to change their choice is missing in the requirements.

> 1.&nbsp;The application is convenient for the user to understand what it can do. (May look just like 'Google form')

"convenient for the user to understand" is not that clear and testable. Try being more clear and objective if that is to be included. Implementation details should be avoided though.

### English

> (May look just like 'Google form')

This isn't a complete sentence and isn't suitable in formal contexts.
A full stop is also missing. In parentheses outside sentences, you should put a complete sentence in. This includes the full stop.

>3.&nbsp;The polls can set the time period.

Grammatically this is correct. But the subject of the sentence, the polls, are doing the setting. This can't be correct! One way to rewrite this sentence would be to change it to a passive form: "The time period of the polls can be set."

**Comment by MaiNorapong** [comment]
Also, this is unrelated to the issue, but

> We are openly for any pull requests, and looking for any userfull features.

I think you need to be working on this by yourself. at least until we are done with it in this course.

**Comment by ZEZAY** [comment]
Thank you :)

**Comment by MaiNorapong** [comment]
Just noticed this, but you should also include what constitutes a poll (i.e. a question and choices) in the requirements as well, other than the period when it's open.
